Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,6 +46,42 @@ jobs:
           echo "Step 2: Running schemachange"
           schemachange -f $GITHUB_WORKSPACE/Setup -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.Streamlit_CHANGE_HISTORY --create-change-history-table
 
+
+      - name: 'Create config'
+        shell: bash
+        env:
+            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWCLI_PW }}
+            
+        
+        run: |
+          # mkdir -p ~/.snowflake
+          # cp config.toml ~/.snowflake/config.toml
+          # echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+          # chmod 0600 ~/.snowflake/config.toml
+  
+  
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+                mkdir -p ~/.snowflake
+                cp ./prod/config.toml ~/.snowflake/config.toml
+                echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+                chmod 0600 ~/.snowflake/config.toml
+                
+          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+                mkdir -p ~/.snowflake
+                cp ./dev/config.toml ~/.snowflake/config.toml
+                echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+                chmod 0600 ~/.snowflake/config.toml
+                
+          elif [[ "${{ github.ref_name }}" == "test" ]]; then
+                mkdir -p ~/.snowflake
+                cp ./test/config.toml ~/.snowflake/config.toml
+                echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+                chmod 0600 ~/.snowflake/config.toml
+          else
+                echo "Invalid branch for deployment"
+          exit 1
+          fi
+          
       - name: 'Deploy the Streamlit app'
         shell: bash
         run: |
